---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: win
autosplit: true
retryOnFailure: false
maxRetries: 1
concurrency: 1
pre:
  - npm install
  - npx playwright install
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: grep -lr 'test' tests
testRunnerCommand: npm test -- $test

jobLabel: [playwright-mv, win, autosplit]

mergeArtifacts: true
    
report: true

partialReports:
 location: Report
 type: html
 
frameworkName: extent

captureScreenRecordingForScenarios: true



 